# Usage: make sure parsed.shelve exists at correct path, then simply run the script
# parsed.data is generated by Sentiment/parse_result.py,
# which uses data collected from twitter cralwer and sentiment result

__author__ = 'bill.yang'

import shelve
from firebase import Firebase

parsed_db = shelve.open('parsed.data')
parsed_data = parsed_db['data']

f = Firebase('http://demo.firebase.com/seifeet/twitter_data_2')
for key, value in parsed_data.items():
    f.push(value)

